from fpdf import FPDF

def create_pdf_report(patient_name, age, risk_score, prediction, top_features, model_name):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt=f"BreathScan AI - Clinical Report", ln=1, align='C')
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(200, 10, txt=f"Model Architecture: {model_name}", ln=1, align='C')
    pdf.ln(10)
    
    # Patient
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Patient: {patient_name} (Age: {age})", ln=1)
    pdf.ln(5)
    
    # Diagnosis
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="AI Assessment Results", ln=1)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Diagnosis: {prediction}", ln=1)
    pdf.cell(200, 10, txt=f"Confidence Score: {risk_score:.2%}", ln=1)
    pdf.ln(10)
    
    # Biomarkers
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Top Contributing Biomarkers", ln=1)
    pdf.set_font("Arial", size=12)
    
    for feat, val in top_features.items():
        pdf.cell(200, 10, txt=f"- {feat}: {val:.4f} impact", ln=1)
        
    # Disclaimer
    pdf.ln(20)
    pdf.set_font("Arial", 'I', 8)
    pdf.multi_cell(0, 10, "Generated by BreathScan AI. This is a decision support tool, not a definitive diagnosis.")
    
    return pdf.output(dest='S').encode('latin-1')